### PR TITLE
Siemens mMR_ACR updates

### PR DESCRIPTION
**Pull request by KrisThielemans**
This PR provides updates using @pjmark's files

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@pjmark, the registered mu-map that you created does not contain the bed. Is that correct? (Looks like we have some bias due to that).

**Comment by pjmark** [comment]
> @pjmark, the registered mu-map that you created does not contain the bed. Is that correct? (Looks like we have some bias due to that).

Yes, you need your the hardware mu-map in addition, which you can generate from the raw data/e7tools

**Comment by pjmark** [comment]
From the images, I can defo say the hardware mu-map is needed.  And yes a bit too smooth.

For the sampling masks, they are many concentric rings, going from the centre to the outside of any insert.  This can be simplified for your case, i.e., using only the masks which cover just the insert without concentric sampling

**Comment by pjmark** [comment]
on second thought, the images look the 'other way' round without the attenuation of the bed... something is not right. But still the bed is needed.

**Comment by pjmark** [comment]
> Sadly, this is one of many things that we have neglected. Obviously, the exact location of the hardware mumap is important (including z-shifts). @NicoleJurjew started looking at this recently but is on holiday.

I could generate it and then remap it to the space of your NIfTI. Do you think you may have some extra shifts?

**Comment by KrisThielemans** [comment]
> could generate it and then remap it to the space of your NIfTI. Do you think you may have some extra shifts?

that'd be amazing. As long as your "complete" mu-map is self-consistent, I guess the remapping has to work.

**Comment by pjmark** [comment]
> that'd be amazing. As long as your "complete" mu-map is self-consistent, I guess the remapping has to work.

I did it!  I'm pretty sure it's correct.  I will send you an email with the NIfTI hardware mu-map.  You just need to add the object and hardware together and it should work.  I would start with the old trusted EMML/OSEM perhaps to see if we are artefact free.

**Comment by KrisThielemans** [comment]
Thanks a lot @pjmark . OSEM full count with some smoothing looks good now!
image

**Comment by KrisThielemans** [comment]
This should be ready now. I'm constructing the reference image.

@casperdcl maybe you do the `lint` etc? I've removed some redundancy in finding file locations, but there's plenty still in other places.

**Comment by KrisThielemans** [comment]
image
Top-left: OSEM 1800s, Top-right: OSEM 200s, Bottom-left: BSREM with RDP 200s

**Comment by KrisThielemans** [comment]
Plots obtained with `plot_BSREM_metrics.py` using a reference image obtained with `run_BSREM` after 21920 updates:
## objective function
Siemens_mMR_ACR_BSREM_objectives
Siemens_mMR_ACR_BSREM_objectives_last
## metrics
Siemens_mMR_ACR_metrics_BSREM_OSEM
Siemens_mMR_ACR_metrics_BSREM
## Images
Siemens_mMR_ACR_OSEM_diff_image_at_0 01_0 005
Siemens_mMR_ACR_ref_diff_image_at_0 01_0 005
Siemens_mMR_ACR_image_at_0 01_0 005

**Pull request merged**
